### ISSUE TITLE
Getting HTTP 403 – Forbidden error for non admin users

### ISSUE THREAD

**Issue by WHITE-developer** [sjelfull/craft3-beam#11]
When exporting an csv with a user that doesn't have full admin permissions we get the `HTTP 403 – Forbidden` error reported from `/vendor/craftcms/cms/src/web/Application.php` on line 275 which checks if the user has access to the plugin.

Craft 3.1.23
Beam 2.1.3

**Comment by sjelfull** [comment]
The Beam controller doesn't require a user to be logged in or checks permissions. Could you paste the stack trace for that error?

**Comment by WHITE-developer** [comment]
Yes I can (/admin/beam/download?hash=longHashCodeHere):
```
yii\web\ForbiddenHttpException in /var/www/html/vendor/craftcms/cms/src/web/Application.php:275
Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#1 /var/www/html/web/index.php(46): yii\base\Application->run()
#2 {main}
```

**Comment by sjelfull** [comment]
Where are you running the Twig code? It looks like its trying to run it through the control panel, which checks permissions.

I'll have a fix out soon that makes sure its always trying to run it through the site instead.

**Comment by WHITE-developer** [comment]
Yes it was in the control panel. Now it's fixed, thanks!
