### ISSUE TITLE
Number Stored as Text?

### ISSUE THREAD

**Issue by jacobgraf** [sjelfull/craft3-beam#12]
When opening a generated XLS in Excel, there are a lot of errors showing up that say "Number Stored as Text". Is there a way to set the format of columns so, for example, dollars are formatted as numbers instead of a string?

**Comment by sjelfull** [comment]
That isn't supported at the moment, but it would be relatively easy to add in the next release.

There is an example in the [PHP_XLSXWriter docs](https://github.com/mk-j/PHP_XLSXWriter), under Simple/Advanced Cell Formats.

Would be sweet if you are able to submit a PR.

**Comment by bartrylant** [comment]
This is 2,5 years old now, but still relevant I think? My client uses this to get an index from all commerce products but has to set the column type to number every time she downloads an Excel file. Would be good to be able to set the column to number with Beam.

**Comment by sjelfull** [comment]
3.0.0 is out with this change.

Check the readme for examples.
