### ISSUE TITLE
Array and string offset access syntax with curly braces is deprecated

### ISSUE THREAD

**Issue by bartrylant** [sjelfull/craft3-beam#14]
When trying to make an Excel sheet, I get an error saying 
`Array and string offset access syntax with curly braces is deprecated`

It seems this is something in `mk-j/php_xlsxwriter/xlsxwriter.class.php`

Line 293
`} elseif (is_string($value) && $value{0}=='='){`

**Comment by torgeirbeyer** [comment]
Same here. 

PHP 7.4.15
Craft 3.15.17.1
Beam 2.5.1

**Comment by philsturgeon** [comment]
This was fixed here https://github.com/mk-j/PHP_XLSXWriter/pull/257/commits/55dd3366da103f6f50ef4b1aa9569ec62a8ceec9 and released in v0.38.

**Comment by sjelfull** [comment]
3.0.0 is out with this fix.
