### ISSUE TITLE
Variable in filename

### ISSUE THREAD

**Issue by marcelvillerius** [sjelfull/craft3-beam#16]
Hi, thank you for this great plugin!

In Craft 4, the variable in the filename does not work as expected. Is there something changed?

```
{% set currentDate = now|date('Y-m-d') %}
{% do beam.setFilename('report-#{currentDate}') %}
```

**Comment by mark-chief** [comment]
@marcelvillerius try this...

```
{% set currentDate = now|date('Y-m-d') %}
{% do beam.setFilename('report-#' ~currentDate) %}
```

**Comment by sjelfull** [comment]
@marcelvillerius Using double quotes is required for Twig/PHP to parse the variable with string interpolation.

```twig
{% set currentDate = now|date('Y-m-d') %}
{% do beam.setFilename("report-#{currentDate}") %}
```

Alternatively you could use @mark-chief's approach
