### ISSUE TITLE
CSV output fails with league/csv 8.2

### ISSUE THREAD

**Issue by rogerdawkins** [sjelfull/craft3-beam#9]
Just upgraded to 2.1.1 and using league/csv 8.2 for compatibility with FeedMe but it fails with:

Call to undefined method League\Csv\Writer::getContent()

in BeamService.php on line 69.

getContent I believe was added in league/csv 9.1 which would explain why it fails.

**Comment by codyjames** [comment]
I'm getting this issue as well.

**Comment by sjelfull** [comment]
Doh, I added it too quickly.

I'll see if I can get Feed Me to upgrade it on their end.

**Comment by codyjames** [comment]
@sjelfull Yeah, I think that is the way to go.

**Comment by codyjames** [comment]
I had to downgrade beam to 2.0.0 in order to use Feed Me and Beam at the same time.

**Comment by wbrowar** [comment]
@nystudio107 also uses league/csv 8.2 for nystudio107/craft-retour, and that's actually where my issue comes from. Is it possible to fall back to the 8.x version methods if 9.x isn't installed or does the new setup prevent that?

**Comment by sjelfull** [comment]
Can't remember if I need anything that isn't in 8.2. I have to take a look at it once I have a moment.

**Comment by rogerdawkins** [comment]
You would need changes to go back to 8.2 for CSV as you use League\Csv\Writer::getContent()

in BeamService.php on line 69.

getContent I believe was added in league/csv 9.1.

**Comment by sjelfull** [comment]
Tagged release with check that hopefully allows both versions to be used.

It basically checks if `getContent` is available, and if not fall backs to using `__toString()`.
